server:
  port: 8808
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_zx_guarantee?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&userSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root

sign:
  appid: xinbao_prod
  appkey: 1111111111111111111

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #mybatis 日志 sql语句打印
  mapper-locations: classpath*:com/ahzx/baohanapi/mapper/xml/*.xml
