server:
  port: 8809

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_zx_guarantee?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&userSSL=false
    username: root
    password: root

sign:
  appId: baohan_pro
  appkey: 111111111111111
  keySecret: 11
  accessKeyId: 11
