server:
  port: 8808
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_zx_guarantee?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&userSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
